apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnet-deployment
  namespace: mssql
#--Ajouter une App OpenShift et pas seulement un Deployment
  labels:
    app: aspnet-deployment
    app.kubernetes.io/component: aspnet-deployment
    app.kubernetes.io/instance: aspnet-deployment
    app.kubernetes.io/part-of: myaspnet
#--
spec:
  selector:
    matchLabels:
      app: aspnet-deployment
#      version: v15.0
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: aspnet-deployment
#        version: v15.0
    spec:
      containers:
        - name: aspnet-container
          image: "mcr.microsoft.com/dotnet/core/samples:aspnetapp"
          ports:
            - containerPort: 8080
          env:
           - name: ASPNETCORE_URLS
             value: "http://+:8080"
#Attention: command pas toujours accepte par image (idem que CMD dans Dockerfile)
          command: ["dotnet"]
          args: ["/app/aspnetapp.dll"]

#oc get deploy //list les deployment
#oc expose deploy aspnet-deployment //create service possible de specifier le nom du svc avec --name
#oc expose service aspnet-deployment //create route plusieurs type de route simple (expose), edge (create route), passthrough(create route), re-encrypt (create route) depend si TLS utilise
