FROM mariadb:10.6
ENV MYSQL_ROOT_PASSWORD=pass
RUN chown -R mysql:mysql /var/lib/mysql && chmod +rw /var/lib/mysql
RUN touch  /var/lib/mysql/testfile
RUN ls -la /var/lib/mysql
EXPOSE 3306
USER mysql
CMD ["mysqld"]
